devide: 
  type: equal_1_2_2
  allocate: by_size
param: 
  file_ratio: 128
  given_size: 0     
log: 
  project_name: vessel
  stdlog: true
  tensorboard: true
reproduc: 
  seed: 42
  benchmark: false
  deterministic: true
compress: 
  loss: 
    otype: L2
  optimizer: 
    otype: Adam
    learning_rate: 1e-3
    beta1: 0.9
    beta2: 0.99
    epsilon: 1e-8
    l2_reg: 1e-8
  encoding: 
    otype: Identity
    scale: 1.0
    offset: 0.0
  network:
    otype: CutlassMLP
    activation: Sine
    output_activation: None
    n_neurons: 16
    n_hidden_layers: 7
  data:
    path: data/example/vessel-0_64-0_512-0_512.tif
    normalized_min: 0
    normalized_max: 100
  weight_intensity_min: 0
  weight_intensity_max: 65535
  weight_val: 1
  coord_normalized_min: -1.0
  coord_normalized_max: 1.0
  n_print_loss_interval: 100
  n_training_samples_upper_limit: 1000000
  n_random_training_samples_of_data_size: 0.0
  n_inference_batch_size: 100000
  n_training_steps: 80000
  compressed_path: test.msgpack
  decompressed_path: test.tif